### ISSUE TITLE
Displaytag & JEE10 / jakarta namespace

### ISSUE THREAD

**Issue by ArthurBorsboom** [hazendaz/displaytag#528] opened 2023-03-14 10:20 UTC
Hi,

I have tried to replace my customized DisplayTag code by dropping in the Displaytag 2.5.1 by Maven provided here.

https://mvnrepository.com/artifact/com.github.hazendaz/displaytag/2.5.1

When I start the servlet container (Wildfly 27), it reports many errors of missing javax classes, for example

```
java.lang.NoClassDefFoundError: Failed to link org/displaytag/tags/ColumnTag (Module "deployment.flint.war" from Service Module Loader): javax/servlet/jsp/tagext/BodyTagSupport
```

Is the migration to the jakarta namespace still ongoing?
Or should it have worked?

**Comment by hazendaz** [comment] 2023-03-14 10:49
Use 3.0.0-M1.  Released yesterday for jakarta.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Arthur Borsboom ***@***.***>
Sent: Tuesday, March 14, 2023 6:21:04 AM
To: hazendaz/displaytag ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hazendaz/displaytag] Displaytag & JEE10 / jakarta namespace (Issue #528)


Hi,

I have tried to replace my customized DisplayTag code by dropping in the Displaytag 2.5.1 by Maven provided here.

When I start the servlet container (Wildfly 27), it reports many errors of missing javax classes, for example

java.lang.NoClassDefFoundError: Failed to link org/displaytag/tags/ColumnTag (Module "deployment.flint.war" from Service Module Loader): javax/servlet/jsp/tagext/BodyTagSupport


Is the migration to the jakarta namespace still ongoing?
Or should it have worked?

**Comment by ArthurBorsboom** [comment] 2023-03-14 16:18
don't see a newer version than 2.5.1 in Maven yet, so I will wait a couple more weeks.
Thanks for the swift response.

**Comment by hazendaz** [comment] 2023-03-14 18:39
It's in central since yesterday.  The index is always behind but does show it currently at 3.0.0-M1

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hazendaz** [comment] 2023-03-17 02:23
any chance you precompiled your jsp with prior versions?  Not sure what the issue is otherwise off hand.  Will be some time before I get far enough to pick this up over at psi-probe repo to see if same issue there.  Few weeks anyways..

**Comment by ArthurBorsboom** [comment] 2023-03-17 09:10
I am not aware of precompiling any JSP's, but maybe this happens without my knowledge.
I have tried it again and indeed, this time it seems to work. :)

I do get new warnings, which might originate from the DisplayTag module.

```
WARN  (): Using deprecated '-debug' fallback for parameter name resolution. Compile the affected code with '-parameters' instead or avoid its introspection: com.xxxx.xxxx.project.base.ProjectController
```

Any chance this is coming from the DisplayTag library?

**Comment by ArthurBorsboom** [comment] 2023-03-17 09:13
Hang on... let me first do my own homework ;-)

**Comment by ArthurBorsboom** [comment] 2023-03-17 09:39
I suspect it is a warning coming from the Spring 6 framework triggered by Spring code in the Displaytag library.
Possibly the Displaytag library has been compiled with the wrong parameter.

> LocalVariableTableParameterNameDiscoverer is deprecated now and logs a warning for each successful resolution attempt (it only kicks in when StandardReflectionParameterNameDiscoverer has not found names). Compile your Java sources with the common Java 8+ -parameters flag for parameter name retention (instead of relying on the -debug compiler flag) in order to avoid that warning, or report it to the maintainers of the affected code.

Source: https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-6.x

If this is indeed the cause and solution, then would you mind to recompile the library and publish it to Maven?

**Comment by ArthurBorsboom** [comment] 2023-03-17 09:48
Ignore that. :)
I have found that I need to compile _my project_ with the necessary parameter.

```
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-compiler-plugin</artifactId>
<configuration>
	<compilerArgs>
		<arg>-parameters</arg>
	</compilerArgs>
</configuration>
```

Adding the above to pom.xml got rid of the warning.

**Comment by hazendaz** [comment] 2023-03-17 15:23
I plan to move onto a general base-parent pom I used on github projects to cleanup the poms here more.  When I do, that change will be automatic as part of that.  It really should be mavens default but isn't right now.  So in case there are other edge cases that require that, it will be part of the milestone 2.  Thanks for sharing how to resolve downstream though, you may want to send that to readme.md as a faq for spring to assist others.

**Comment by hazendaz** [comment] 2023-08-14 22:02
closing as duplicate issue noted on jakarta per #523 and other items noted here addressed.

**Closed by hazendaz** 2023-08-14 22:02 UTC
